# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envguard < Formula
  desc "Zero-config pre-commit secret scanner for Git repositories."
  homepage "https://github.com/Sophylax/envguard"
  version "0.0.1-test1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Sophylax/envguard/releases/download/v0.0.1-test1/envguard_0.0.1-test1_darwin_amd64.tar.gz"
      sha256 "87a8d124e7d63cd0cb4902b0cc29d4d85ae119e0249bc4b5382f48b4912e50a1"

      define_method(:install) do
        bin.install "envguard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Sophylax/envguard/releases/download/v0.0.1-test1/envguard_0.0.1-test1_darwin_arm64.tar.gz"
      sha256 "52edbc9b07e15bf55b41462ddca34b14ed4311e45d82cd83e3685cb749c3197c"

      define_method(:install) do
        bin.install "envguard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sophylax/envguard/releases/download/v0.0.1-test1/envguard_0.0.1-test1_linux_amd64.tar.gz"
      sha256 "a47add6fe8c3de9b8a9ca85a27feb2b030616c94c19da027ac8218cffe0bbe1e"
      define_method(:install) do
        bin.install "envguard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sophylax/envguard/releases/download/v0.0.1-test1/envguard_0.0.1-test1_linux_arm64.tar.gz"
      sha256 "afd6ca08fd9a566262e7cbe8047b76c6f763a213227229d787cad3c98824f744"
      define_method(:install) do
        bin.install "envguard"
      end
    end
  end
end
