# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envguard < Formula
  desc "Zero-config pre-commit secret scanner for Git repositories."
  homepage "https://github.com/Sophylax/envguard"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Sophylax/envguard/releases/download/v0.1.1/envguard_0.1.1_darwin_amd64.tar.gz"
      sha256 "528d66100e74ae9add35dc6b4bf8632ae7779e482756283a71cd3c315da448dc"

      define_method(:install) do
        bin.install "envguard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Sophylax/envguard/releases/download/v0.1.1/envguard_0.1.1_darwin_arm64.tar.gz"
      sha256 "ab33982f72907e5346bb504f9b7b97c5d6f0f2dda9fbd2aeb70186ee329d0ece"

      define_method(:install) do
        bin.install "envguard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sophylax/envguard/releases/download/v0.1.1/envguard_0.1.1_linux_amd64.tar.gz"
      sha256 "a4f6fbd7462036b5e1979032ef2d5e2a42b5888ef8bdaaef5c57aecfbefd57a7"
      define_method(:install) do
        bin.install "envguard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sophylax/envguard/releases/download/v0.1.1/envguard_0.1.1_linux_arm64.tar.gz"
      sha256 "006f358d79379ede23890f2ee1f8f5a87e0cb05ce4b20622bbf70a23ccbb1240"
      define_method(:install) do
        bin.install "envguard"
      end
    end
  end
end
